image: "redoxos/redox"

stages:
    - build
    - test

before_script:
    - rustup target add x86_64-unknown-redox --toolchain nightly
    - rustup show      # Print version info for debugging

cache:
    paths:
        - target/

build:linux:cargo:
    stage: build
    script: cargo +nightly build --verbose

build:redox:cargo:
    stage: build
    script: 
        - mkdir .cargo
        - echo -e "[target.x86_64-unknown-redox]\nlinker = \"x86_64-unknown-redox-gcc\"" > .cargo/config
        - cargo +nightly build --verbose --target x86_64-unknown-redox

test:linux:cargo:
    stage: test
    dependencies: 
        - build:linux:cargo
    script: cargo +nightly test --verbose

# TODO: Set up a docker image with a redox vm that would allow to
#   run things like tests under redox
