[package]
name = "redoxfs"
description = "The Redox Filesystem"
repository = "https://github.com/redox-os/redoxfs"
version = "0.2.0"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "redoxfs"
path = "src/lib.rs"

[[bin]]
name = "redoxfs"
path = "src/bin/mount.rs"

[[bin]]
name = "redoxfs-mkfs"
path = "src/bin/mkfs.rs"

[dependencies]
spin = { git = "https://github.com/messense/spin-rs", rev = "020f1b3f" }
redox_syscall = "0.1"

[target.'cfg(unix)'.dependencies]
fuse = "0.3"
libc = "0.2"
time = "0.1"
