[package]
name = "redoxfs"
description = "The Redox Filesystem"
repository = "https://github.com/redox-os/redoxfs"
version = "0.1.1"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "redoxfs"
path = "src/lib.rs"

[[bin]]
name = "redoxfs"
path = "mount/main.rs"

[[bin]]
name = "redoxfs-mkfs"
path = "mkfs/main.rs"

[dependencies]
spin = "*"
redox_syscall = { git = "https://github.com/redox-os/syscall.git" }

[target.'cfg(unix)'.dependencies]
fuse = "0.2"
time = "*"
